#!/usr/bin/env python3
"""Load production catalogue data from content/ into Supabase.

Sources (gitignored, generated by scripts/):
  content/tables/{projects,curators,venues}.json  — 2025–26 sheet catalogue
  content/site-content.json                       — editions, about, programmes, press
  content/media-manifest.json                     — Drive asset metadata (no upload)

Catalogue tables are import-owned. Programmes, press, and about upsert but are
also CMS-editable after load.

Usage (from repo root):
  python3 backend/import_catalogue.py --dry-run
  python3 backend/import_catalogue.py --target linked
  python3 backend/import_catalogue.py --target local
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import unicodedata
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content"
TABLES = CONTENT / "tables"
SQL_OUT = ROOT / "database" / "supabase" / ".temp" / "catalogue_import.sql"
EDITION_ID = "edition-2025-26"
PUBLIC_SUPABASE_URL = "https://ozexvctgofwxcikvcxwg.supabase.co"

EDITION_META = [
    ("edition-2014-15", 1, "2014-15", "The Students’ Biennale"),
    ("edition-2016-17", 2, "2016-17", "Later the atelier ate her"),
    ("edition-2018-19", 3, "2018-19", "Making as Thinking"),
    ("edition-2020-21", 4, "2020-21", "States of Disarray: Practice as Restitution"),
    ("edition-2022-23", 5, "2022-23", "In the Making"),
    ("edition-2025-26", 6, "2025-26", "Sensing Grounds"),
]

VENUE_ALIASES = {
    "venue-vkl-warehouse": "venue-vkl-warehouse",
    "venue-vkl": "venue-vkl-warehouse",
    "venue-david-hall": "venue-david-hall",
    "venue-arthshila-kochi": "venue-arthshila-kochi",
    "venue-arthshila": "venue-arthshila-kochi",
    "venue-space": "venue-space",
    "venue-space-gallery": "venue-space",
    "venue-space-indian-chamber-of-commerce": "venue-space",
    "venue-bms-warehouse": "venue-bms-warehouse",
    "venue-brights-warehouse": "venue-bms-warehouse",
    "venue-brights-warehouse-bms": "venue-bms-warehouse",
    "venue-st-andrews-parish-hall": "venue-st-andrews-parish-hall",
    "venue-st-andrew-s-parish-hall": "venue-st-andrews-parish-hall",
    "venue-parish-hall": "venue-st-andrews-parish-hall",
}

VENUE_NAMES = {
    "venue-vkl-warehouse": "VKL Warehouse",
    "venue-bms-warehouse": "BMS Warehouse",
    "venue-st-andrews-parish-hall": "St. Andrew's Parish Hall",
    "venue-arthshila-kochi": "Arthshila Kochi",
    "venue-david-hall": "David Hall",
    "venue-space": "SPACE",
}

VENUE_NAME_TO_ID = {
    "vkl warehouse": "venue-vkl-warehouse",
    "bms warehouse": "venue-bms-warehouse",
    "st. andrews parish hall": "venue-st-andrews-parish-hall",
    "st. andrew's parish hall": "venue-st-andrews-parish-hall",
    "arthshila kochi": "venue-arthshila-kochi",
    "space": "venue-space",
    "david hall": "venue-david-hall",
}

URL_RE = re.compile(r"https?://[^\s<>\"]+")
FACILITATORS_RE = re.compile(r"facilitators?:\s*(.+)", re.I | re.S)
MONTHS = (
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
)


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value or "")
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii").lower()
    return re.sub(r"[^a-z0-9]+", "-", ascii_text).strip("-")


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    text = "\n".join(line.rstrip() for line in text.splitlines())
    return text.strip()


def one_line(value: Any) -> str:
    return re.sub(r"\s+", " ", clean_text(value)).strip()


def card_storage_path(path: str) -> str:
    rel = path.removeprefix("media/").lstrip("/")
    parts = [ "card" if part == "original" else part for part in Path(rel).parts ]
    return str(Path(*parts).with_suffix(".jpg"))


def public_asset_url(storage_path: str) -> str:
    return f"{PUBLIC_SUPABASE_URL}/storage/v1/object/public/sb-assets-public/{storage_path}"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def person_id(name: str) -> str:
    slug = slugify(name) or "unknown"
    return f"person-{slug}"


def institution_id(name: str) -> str:
    slug = slugify(name) or "unknown"
    return f"institution-{slug}"


def canon_venue_id(raw_id: str) -> str:
    key = raw_id if raw_id.startswith("venue-") else f"venue-{raw_id}"
    return VENUE_ALIASES.get(key, key)


def venue_id_from_name(name: str) -> str | None:
    if not name:
        return None
    return VENUE_NAME_TO_ID.get(name.strip().lower())


def is_collective(name: str) -> bool:
    lowered = name.lower().strip()
    return lowered == "gabaa" or "collective" in lowered


def split_assistant_names(value: str) -> list[str]:
    if not value:
        return []
    parts = re.split(r"\s+and\s+|,\s*", value, flags=re.I)
    return [one_line(part) for part in parts if one_line(part)]


def first_urls(*values: str) -> str | None:
    for value in values:
        found = URL_RE.findall(value or "")
        if found:
            return found[0].rstrip(".,);")
    return None


def extract_urls(*values: str) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        for match in URL_RE.findall(value or ""):
            url = match.rstrip(".,);")
            if url not in seen:
                seen.add(url)
                out.append(url)
    return out


def unique_slug(taken: set[str], desired: str, prefix: str) -> str:
    slug = desired or prefix
    if slug not in taken:
        taken.add(slug)
        return slug
    n = 2
    while f"{slug}-{n}" in taken:
        n += 1
    slug = f"{slug}-{n}"
    taken.add(slug)
    return slug


def section_paragraphs(section: dict[str, Any]) -> list[str]:
    texts: list[str] = []
    for para in section.get("paragraphs") or []:
        if isinstance(para, dict):
            text = clean_text(para.get("text"))
        else:
            text = clean_text(para)
        if text:
            texts.append(text)
    return texts


def section_urls(section: dict[str, Any]) -> list[str]:
    urls: list[str] = []
    for para in section.get("paragraphs") or []:
        if not isinstance(para, dict):
            continue
        urls.extend(para.get("links") or [])
        urls.extend(extract_urls(para.get("text") or ""))
    seen: set[str] = set()
    out: list[str] = []
    for url in urls:
        if url not in seen:
            seen.add(url)
            out.append(url)
    return out


def looks_like_location(text: str) -> bool:
    line = one_line(text)
    if not line or len(line) > 90:
        return False
    return any(month in line for month in MONTHS)


def parse_location(text: str) -> tuple[str, str]:
    line = one_line(text)
    year = re.search(r"(20\d{2}(?:\s*[–-]\s*20\d{2})?)", line)
    return line, (year.group(1) if year else "")


def parse_workshop_section(section: dict[str, Any]) -> dict[str, Any]:
    heading = clean_text(section.get("heading") or "").lstrip("✅ ").strip()
    texts = section_paragraphs(section)
    urls = section_urls(section)
    title = ""
    facilitators_raw = ""
    place = ""
    dates = ""
    body_parts: list[str] = []

    lines: list[str] = []
    for text in texts:
        lines.extend(part.strip() for part in text.split("\n") if part.strip())

    for line in lines:
        if re.match(r"^images?:", line, re.I) or line.startswith("http"):
            continue
        fac = FACILITATORS_RE.search(line)
        if fac:
            facilitators_raw = one_line(fac.group(1))
            before = one_line(FACILITATORS_RE.split(line)[0].strip(" :"))
            if before and not title:
                title = before
            continue
        if looks_like_location(line) and not place:
            place, dates = parse_location(line)
            continue
        if not title:
            title = one_line(line)
            continue
        body_parts.append(line)

    if not title or title.endswith("…"):
        title = heading or title or "Workshop"
    body = "\n\n".join(body_parts).strip()
    summary = one_line(body)[:280]
    slug = slugify(section.get("id") or title)
    return {
        "id": f"programme-workshop-{slug}",
        "subtype": "workshop",
        "state": "past",
        "title": title,
        "slug": slug,
        "summary": summary,
        "body": body,
        "dates": dates,
        "place": place,
        "facilitators_raw": facilitators_raw,
        "image_urls": urls,
        "source_heading": heading,
    }


def parse_awardees(paragraphs: list[str]) -> list[dict[str, str]]:
    winners: list[dict[str, str]] = []
    current: dict[str, str] = {}
    lines: list[str] = []
    for raw in paragraphs:
        lines.extend(part.strip() for part in clean_text(raw).split("\n") if part.strip())

    def flush() -> None:
        nonlocal current
        if current.get("name"):
            winners.append(current)
        current = {}

    for text in lines:
        if text.startswith("http") or text.lower().startswith("link to"):
            continue
        if text.lower().startswith("tata trusts") or text.lower().startswith("format"):
            continue
        artwork = re.match(r"(?:artwork title|artwork):\s*(.+)", text, re.I)
        institution = re.match(r"institution:\s*(.+)", text, re.I)
        if artwork:
            current["artwork"] = one_line(artwork.group(1))
            continue
        if institution:
            current["institution"] = one_line(institution.group(1))
            flush()
            continue
        flush()
        current = {"name": one_line(text)}
    flush()
    return winners


def winners_body(winners: list[dict[str, str]]) -> str:
    lines: list[str] = []
    for winner in winners:
        bit = winner.get("name") or ""
        if winner.get("artwork"):
            bit += f" — {winner['artwork']}"
        if winner.get("institution"):
            bit += f" ({winner['institution']})"
        lines.append(f"- {bit}")
    return "\n".join(lines)


def edition_section_key(heading: str, edition_title: str) -> str:
    h = (heading or "").lower()
    if "curatorial note" in h:
        return "curatorial_note"
    if "curator" in h:
        return "curators"
    if "team" in h or "institution" in h:
        return "team"
    if "image" in h or "caption" in h or "gallery" in h:
        return "gallery"
    if "download" in h or "pdf" in h:
        return "downloads"
    if "press" in h:
        return "press"
    if "resource" in h:
        return "resources"
    if heading and edition_title and heading.lower() == edition_title.lower():
        return "overview"
    if "students" in h and "biennale" in h:
        return "overview"
    if heading == "Sensing Grounds":
        return "curatorial_note"
    return "custom"


def split_2025_overview(paragraphs: list[str]) -> tuple[str, str]:
    overview: list[str] = []
    note: list[str] = []
    seen_title = False
    for para in paragraphs:
        if one_line(para) == "Sensing Grounds":
            seen_title = True
            continue
        if seen_title:
            note.append(para)
        else:
            overview.append(para)
    return "\n\n".join(overview).strip(), "\n\n".join(note).strip()


def format_team_body(lines: list[str]) -> str:
    rows: list[str] = []
    current_role = ""
    for line in lines:
        text = one_line(line).rstrip(":")
        if not text or text.startswith("⚠️"):
            continue
        if text.endswith(":") or text in {
            "Director of Programmes",
            "Programme Managers",
            "Programmes Assistants",
            "Production Managers",
            "Production Assistants",
            "Accounts Manager",
            "Social Media",
            "Social Media and Catalogue",
        }:
            current_role = text.rstrip(":")
            continue
        if current_role:
            rows.append(f"- {current_role}: {text}")
        else:
            rows.append(f"- {text}")
    return "\n".join(rows)


WEB_ASSET_VARIANTS = ("card", "hero", "thumbnail", "gallery")


def _compact_search_entry(entry: dict[str, Any]) -> dict[str, Any]:
    row: dict[str, Any] = {
        "entity_type": entry["entity_type"],
        "entity_id": entry["entity_id"],
        "title": entry["title"],
        "route": entry["route"],
    }
    for key in (
        "subtitle",
        "field_title",
        "field_artist",
        "field_curator",
        "field_venue",
        "field_zone",
        "field_institution",
        "field_edition",
    ):
        value = entry.get(key)
        if value:
            row[key] = value
    return row


def _linked_assets(
    links_by_entity: dict[tuple[str, str], list[dict[str, Any]]],
    assets_by_id: dict[str, dict[str, Any]],
    entity_type: str,
    entity_id: str,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for link in links_by_entity.get((entity_type, entity_id), []):
        asset = assets_by_id.get(link["asset_id"])
        if not asset:
            continue
        out.append({**asset, "role": link.get("role")})
    return out


def _public_cover(assets: list[dict[str, Any]]) -> tuple[str | None, int | None, int | None]:
    ready = [
        a
        for a in assets
        if a.get("status") == "ready"
        and a.get("variant") in WEB_ASSET_VARIANTS
        and a.get("public_url")
    ]
    rank = {name: i for i, name in enumerate(WEB_ASSET_VARIANTS)}
    ready.sort(key=lambda a: (rank.get(a.get("variant"), 9), a.get("sort_order") or 0))
    if not ready:
        return None, None, None
    cover = ready[0]
    return cover.get("public_url"), cover.get("width"), cover.get("height")


def _gallery_urls(assets: list[dict[str, Any]]) -> list[str]:
    urls: list[str] = []
    seen: set[str] = set()
    for asset in assets:
        url = asset.get("public_url")
        if (
            asset.get("status") == "ready"
            and asset.get("variant") in WEB_ASSET_VARIANTS
            and url
            and url not in seen
        ):
            seen.add(url)
            urls.append(url)
    return urls


def build_catalogue_snapshots(payload: dict[str, Any]) -> list[dict[str, Any]]:
    """One denormalized pack per edition for the public site."""
    people_by_id = {p["id"]: p for p in payload["people"]}
    venues_by_id = {v["id"]: v for v in payload["venues"]}
    assets_by_id = {a["id"]: a for a in payload["assets"]}
    links_by_entity: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for link in payload["asset_links"]:
        links_by_entity.setdefault((link["entity_type"], link["entity_id"]), []).append(link)

    contributors_by_artwork: dict[str, list[dict[str, Any]]] = {}
    for row in payload["artwork_contributors"]:
        contributors_by_artwork.setdefault(row["artwork_id"], []).append(row)

    zone_people_by_zone: dict[str, list[dict[str, Any]]] = {}
    for row in payload["zone_people"]:
        zone_people_by_zone.setdefault(row["zone_id"], []).append(row)

    sections_by_edition: dict[str, list[dict[str, Any]]] = {}
    for section in payload["edition_sections"]:
        sections_by_edition.setdefault(section["edition_id"], []).append(section)

    items_by_section: dict[str, list[dict[str, Any]]] = {}
    for item in payload["edition_section_items"]:
        items_by_section.setdefault(item["section_id"], []).append(item)

    search_by_edition: dict[str, list[dict[str, Any]]] = {}
    for entry in payload["search_entries"]:
        eid = entry.get("edition_id")
        if eid:
            search_by_edition.setdefault(eid, []).append(entry)

    edition_venue_ids: dict[str, list[str]] = {}
    for row in payload["edition_venues"]:
        edition_venue_ids.setdefault(row["edition_id"], []).append(row["venue_id"])

    zones_by_edition: dict[str, list[dict[str, Any]]] = {}
    for zone in payload["zones"]:
        zones_by_edition.setdefault(zone["edition_id"], []).append(zone)

    artworks_by_edition: dict[str, list[dict[str, Any]]] = {}
    for artwork in payload["artworks"]:
        artworks_by_edition.setdefault(artwork["edition_id"], []).append(artwork)

    generated_at = payload["imported_at"]
    snapshots: list[dict[str, Any]] = []

    for edition in payload["editions"]:
        eid = edition["id"]
        years = edition["years"]
        zone_rows = sorted(zones_by_edition.get(eid, []), key=lambda z: z.get("number") or 0)
        mapped_zones: list[dict[str, Any]] = []
        for zone in zone_rows:
            curators: list[dict[str, Any]] = []
            assistants: list[dict[str, Any]] = []
            members = sorted(zone_people_by_zone.get(zone["id"], []), key=lambda r: r.get("sort_order") or 0)
            for member in members:
                person = people_by_id.get(member["person_id"]) or {}
                person_assets = _linked_assets(links_by_entity, assets_by_id, "person", member["person_id"])
                cover_url, cover_w, cover_h = _public_cover(person_assets)
                card = {
                    "id": member["person_id"],
                    "name": person.get("name") or member["person_id"],
                    "slug": person.get("slug"),
                    "bio": person.get("bio"),
                    "is_collective": bool(person.get("is_collective")),
                    "individual_curatorial_note": member.get("individual_curatorial_note"),
                    "cover_url": cover_url,
                    "cover_width": cover_w,
                    "cover_height": cover_h,
                }
                if member["role"] == "assistant":
                    assistants.append(card)
                else:
                    curators.append(card)
            mapped_zones.append(
                {
                    "id": zone["id"],
                    "number": zone["number"],
                    "label": zone.get("label") or f"Zone {zone['number']}",
                    "region": zone.get("region"),
                    "common_curatorial_note": zone.get("common_curatorial_note"),
                    "curators": curators,
                    "assistants": assistants,
                }
            )

        mapped_venues: list[dict[str, Any]] = []
        for vid in edition_venue_ids.get(eid, []):
            venue = venues_by_id.get(vid)
            if not venue:
                continue
            venue_assets = _linked_assets(links_by_entity, assets_by_id, "venue", vid)
            cover_url, cover_w, cover_h = _public_cover(venue_assets)
            mapped_venues.append(
                {
                    "id": venue["id"],
                    "slug": venue["slug"],
                    "name": venue["name"],
                    "history": venue.get("history"),
                    "map_url": venue.get("map_url"),
                    "virtual_tour_url": venue.get("virtual_tour_url"),
                    "cover_url": cover_url,
                    "cover_width": cover_w,
                    "cover_height": cover_h,
                    "gallery_urls": _gallery_urls(venue_assets),
                }
            )

        mapped_artworks: list[dict[str, Any]] = []
        artists_by_id: dict[str, dict[str, Any]] = {}
        for artwork in sorted(artworks_by_edition.get(eid, []), key=lambda a: a.get("sort_order") or 0):
            if not artwork.get("published", True):
                continue
            art_assets = _linked_assets(links_by_entity, assets_by_id, "artwork", artwork["id"])
            cover_url, cover_w, cover_h = _public_cover(art_assets)
            venue = venues_by_id.get(artwork.get("venue_id") or "")
            contribs = sorted(
                contributors_by_artwork.get(artwork["id"], []),
                key=lambda c: c.get("sort_order") or 0,
            )
            mapped_contribs = []
            zone = next((z for z in mapped_zones if z["id"] == artwork.get("zone_id")), None)
            for contrib in contribs:
                mapped_contribs.append(
                    {
                        "person_id": contrib.get("person_id"),
                        "display_name": contrib["display_name"],
                        "institution_name": contrib.get("institution_name"),
                        "materials": contrib.get("materials"),
                        "dimensions": contrib.get("dimensions"),
                    }
                )
                pid = contrib.get("person_id")
                if pid and pid not in artists_by_id:
                    artists_by_id[pid] = {
                        "id": pid,
                        "name": contrib["display_name"],
                        "slug": (people_by_id.get(pid) or {}).get("slug"),
                        "institution": contrib.get("institution_name") or "",
                        "zone_id": artwork.get("zone_id"),
                        "zone_label": zone["label"] if zone else None,
                    }
            mapped_artworks.append(
                {
                    "id": artwork["id"],
                    "slug": artwork["slug"],
                    "title": artwork["title"],
                    "description": artwork.get("description"),
                    "materials_summary": artwork.get("materials_summary"),
                    "dimensions_summary": artwork.get("dimensions_summary"),
                    "zone_id": artwork.get("zone_id"),
                    "venue_id": artwork.get("venue_id"),
                    "venue_name": venue["name"] if venue else None,
                    "cover_url": cover_url,
                    "cover_width": cover_w,
                    "cover_height": cover_h,
                    "gallery_urls": _gallery_urls(art_assets),
                    "contributors": mapped_contribs,
                }
            )

        mapped_sections = []
        for section in sorted(sections_by_edition.get(eid, []), key=lambda s: s.get("sort_order") or 0):
            mapped_sections.append(
                {
                    "id": section["id"],
                    "section_key": section["section_key"],
                    "title": section.get("title"),
                    "body": section.get("body"),
                    "sort_order": section.get("sort_order") or 0,
                    "items": [
                        {
                            "label": item.get("label"),
                            "url": item.get("url"),
                            "content_type": item.get("content_type"),
                        }
                        for item in sorted(
                            items_by_section.get(section["id"], []),
                            key=lambda i: i.get("sort_order") or 0,
                        )
                    ],
                }
            )

        edition_assets = _linked_assets(links_by_entity, assets_by_id, "edition", eid)
        hero_url, _, _ = _public_cover(edition_assets)

        pack = {
            "edition": {
                "id": eid,
                "years": years,
                "number": edition["number"],
                "title": edition.get("title"),
                "slug": edition["slug"],
                "overview": edition.get("overview"),
                "overall_curatorial_note": edition.get("overall_curatorial_note"),
                "is_current": edition["is_current"],
                "published": edition["published"],
                "hero_url": hero_url,
                "gallery_urls": _gallery_urls(edition_assets),
            },
            "sections": mapped_sections,
            "zones": mapped_zones,
            "venues": mapped_venues,
            "artworks": mapped_artworks,
            "artists": list(artists_by_id.values()),
        }
        snapshots.append(
            {
                "edition_id": eid,
                "payload": pack,
                "search_index": [_compact_search_entry(e) for e in search_by_edition.get(eid, [])],
                "generated_at": generated_at,
            }
        )

    return snapshots


def build_payload() -> tuple[dict[str, Any], dict[str, int]]:
    site = load_json(CONTENT / "site-content.json")
    projects_raw = load_json(TABLES / "projects.json")
    curators_raw = load_json(TABLES / "curators.json")
    venues_raw = load_json(TABLES / "venues.json")
    media = load_json(CONTENT / "media-manifest.json") if (CONTENT / "media-manifest.json").exists() else {}

    people: dict[str, dict[str, Any]] = {}
    institutions: dict[str, dict[str, Any]] = {}
    slugs_taken: set[str] = set()
    slugs: list[dict[str, Any]] = []
    search_entries: list[dict[str, Any]] = []
    import_sources: list[dict[str, Any]] = []

    def add_person(name: str, bio: str = "", collective: bool | None = None) -> str:
        pid = person_id(name)
        if pid not in people:
            people[pid] = {
                "id": pid,
                "name": one_line(name),
                "slug": unique_slug(slugs_taken, slugify(name), pid),
                "bio": clean_text(bio) or None,
                "is_collective": is_collective(name) if collective is None else collective,
            }
        elif bio and not people[pid].get("bio"):
            people[pid]["bio"] = clean_text(bio)
        return pid

    def add_institution(name: str) -> str | None:
        cleaned = one_line(name.replace("\n", " "))
        if not cleaned:
            return None
        iid = institution_id(cleaned)
        institutions.setdefault(
            iid,
            {"id": iid, "name": cleaned, "slug": unique_slug(slugs_taken, slugify(cleaned), iid)},
        )
        return iid

    def add_slug(slug: str, entity_type: str, entity_id: str, edition_id: str | None) -> None:
        if not slug or slug in {row["slug"] for row in slugs}:
            return
        slugs.append(
            {
                "slug": slug,
                "entity_type": entity_type,
                "entity_id": entity_id,
                "edition_id": edition_id,
            }
        )

    def source(entity_type: str, entity_id: str, source_type: str, ref: str) -> None:
        import_sources.append(
            {
                "entity_type": entity_type,
                "entity_id": entity_id,
                "source_type": source_type,
                "source_ref": ref,
            }
        )

    editions_by_id = {row["id"]: row for row in site.get("editions") or []}
    editions: list[dict[str, Any]] = []
    edition_sections: list[dict[str, Any]] = []
    edition_section_items: list[dict[str, Any]] = []

    for eid, number, years, fallback_title in EDITION_META:
        src = editions_by_id.get(eid, {})
        title = src.get("title") or fallback_title
        overview = clean_text(src.get("overview"))
        note = None
        if eid == EDITION_ID:
            paras = []
            for section in src.get("documentSections") or []:
                paras.extend(section_paragraphs(section))
            overview_split, note = split_2025_overview(paras)
            if overview_split:
                overview = overview_split
        editions.append(
            {
                "id": eid,
                "number": number,
                "years": years,
                "title": title,
                "slug": years,
                "overview": overview or None,
                "overall_curatorial_note": note,
                "is_current": eid == EDITION_ID,
                "published": True,
            }
        )
        add_slug(years, "edition", eid, eid)
        slugs_taken.add(years)
        source("edition", eid, "docx", src.get("canonicalDocument") or "site-content.json")
        search_entries.append(
            {
                "id": f"search-{eid}",
                "entity_type": "edition",
                "entity_id": eid,
                "edition_id": eid,
                "title": title,
                "subtitle": f"Students' Biennale {years}",
                "route": f"/editions/{years}",
                "field_title": title,
                "field_artist": None,
                "field_curator": None,
                "field_venue": None,
                "field_zone": None,
                "field_institution": None,
                "field_edition": years,
                "field_programme": None,
            }
        )

        sort_key = 0
        for section in src.get("documentSections") or []:
            heading = clean_text(section.get("heading"))
            body = "\n\n".join(section_paragraphs(section))
            if not heading and not body:
                continue
            if eid == EDITION_ID and heading == "Sensing Grounds":
                continue
            key = edition_section_key(heading, title)
            sid = f"{eid}-{key}-{sort_key}"
            edition_sections.append(
                {
                    "id": sid,
                    "edition_id": eid,
                    "section_key": key,
                    "title": heading or None,
                    "body": body or None,
                    "sort_order": sort_key,
                }
            )
            for url_i, url in enumerate(section_urls(section)):
                edition_section_items.append(
                    {
                        "id": f"{sid}-item-{url_i}",
                        "section_id": sid,
                        "label": None,
                        "url": url,
                        "content_type": "link",
                        "sort_order": url_i,
                    }
                )
            sort_key += 1

        credits = clean_text(src.get("peopleAndCredits"))
        if credits and eid != EDITION_ID:
            sid = f"{eid}-team-credits"
            if not any(row["id"] == sid for row in edition_sections):
                edition_sections.append(
                    {
                        "id": sid,
                        "edition_id": eid,
                        "section_key": "team",
                        "title": "Team & credits",
                        "body": credits,
                        "sort_order": sort_key,
                    }
                )

    # 2025–26 team from About doc
    about = site.get("about") or {}
    team_section = next(
        (s for s in about.get("documentSections") or [] if "team" in (s.get("heading") or "").lower()),
        None,
    )
    if team_section:
        edition_sections.append(
            {
                "id": f"{EDITION_ID}-team",
                "edition_id": EDITION_ID,
                "section_key": "team",
                "title": "SB Team 2025-26",
                "body": format_team_body(section_paragraphs(team_section)) or None,
                "sort_order": 0,
            }
        )
    if editions[-1]["overall_curatorial_note"]:
        edition_sections.append(
            {
                "id": f"{EDITION_ID}-curatorial-note",
                "edition_id": EDITION_ID,
                "section_key": "curatorial_note",
                "title": "Sensing Grounds",
                "body": editions[-1]["overall_curatorial_note"],
                "sort_order": 1,
            }
        )

    zones: dict[int, dict[str, Any]] = {}
    zone_people: list[dict[str, Any]] = []
    for curator in curators_raw:
        zone_no = int(curator["zoneNumber"])
        zid = f"zone-{zone_no}"
        note = clean_text(curator.get("commonCuratorialNote"))
        if zone_no not in zones:
            zones[zone_no] = {
                "id": zid,
                "edition_id": EDITION_ID,
                "number": zone_no,
                "label": f"Zone {zone_no}",
                "region": clean_text(curator.get("region")) or None,
                "common_curatorial_note": note or None,
                "sort_order": zone_no,
            }
        else:
            if note and len(note) > len(zones[zone_no].get("common_curatorial_note") or ""):
                zones[zone_no]["common_curatorial_note"] = note
            if curator.get("region") and not zones[zone_no].get("region"):
                zones[zone_no]["region"] = clean_text(curator["region"])
        pid = add_person(curator["name"], curator.get("bio") or "")
        zone_people.append(
            {
                "zone_id": zid,
                "person_id": pid,
                "role": "curator",
                "individual_curatorial_note": clean_text(curator.get("individualCuratorialNote")) or None,
                "sort_order": len([r for r in zone_people if r["zone_id"] == zid and r["role"] == "curator"]),
            }
        )
        source("person", pid, "sheet", f"Curators Data row {curator.get('sourceRow')}")
        search_entries.append(
            {
                "id": f"search-{pid}-{zid}",
                "entity_type": "person",
                "entity_id": pid,
                "edition_id": EDITION_ID,
                "title": curator["name"],
                "subtitle": curator.get("region") or f"Zone {zone_no}",
                "route": f"/editions/2025-26/curators/{pid}",
                "field_title": curator["name"],
                "field_artist": None,
                "field_curator": curator["name"],
                "field_venue": None,
                "field_zone": f"Zone {zone_no}",
                "field_institution": None,
                "field_edition": "2025-26",
                "field_programme": None,
            }
        )
        for assistant in split_assistant_names(curator.get("assistant") or ""):
            aid = add_person(assistant)
            zone_people.append(
                {
                    "zone_id": zid,
                    "person_id": aid,
                    "role": "assistant",
                    "individual_curatorial_note": None,
                    "sort_order": len(
                        [r for r in zone_people if r["zone_id"] == zid and r["role"] == "assistant"]
                    ),
                }
            )

    venues: dict[str, dict[str, Any]] = {}
    for index, venue in enumerate(venues_raw):
        vid = canon_venue_id(venue["id"])
        existing = venues.get(vid)
        history = clean_text(venue.get("history"))
        row = {
            "id": vid,
            "slug": vid.removeprefix("venue-"),
            "name": VENUE_NAMES.get(vid) or venue["name"],
            "history": history or None,
            "map_url": (venue.get("mapLinks") or [None])[0],
            "virtual_tour_url": (venue.get("virtualTourLinks") or [None])[0],
            "sort_order": index,
        }
        if existing:
            if history and len(history) > len(existing.get("history") or ""):
                existing["history"] = history
            if row["map_url"] and not existing.get("map_url"):
                existing["map_url"] = row["map_url"]
            if row["virtual_tour_url"] and not existing.get("virtual_tour_url"):
                existing["virtual_tour_url"] = row["virtual_tour_url"]
        else:
            venues[vid] = row
            add_slug(row["slug"], "venue", vid, EDITION_ID)
            slugs_taken.add(row["slug"])
            search_entries.append(
                {
                    "id": f"search-{vid}",
                    "entity_type": "venue",
                    "entity_id": vid,
                    "edition_id": EDITION_ID,
                    "title": row["name"],
                    "subtitle": "Venue · 2025-26",
                    "route": f"/editions/2025-26/venue/{vid}",
                    "field_title": row["name"],
                    "field_artist": None,
                    "field_curator": None,
                    "field_venue": row["name"],
                    "field_zone": None,
                    "field_institution": None,
                    "field_edition": "2025-26",
                    "field_programme": None,
                }
            )
        source("venue", vid, "sheet", f"Venue Data row {venue.get('sourceRow')}")

    for venue in site.get("venues") or []:
        vid = canon_venue_id(venue["id"])
        if vid not in venues:
            venues[vid] = {
                "id": vid,
                "slug": vid.removeprefix("venue-"),
                "name": VENUE_NAMES.get(vid) or venue["name"],
                "history": clean_text(venue.get("history")) or None,
                "map_url": (venue.get("mapLinks") or [None])[0],
                "virtual_tour_url": None,
                "sort_order": len(venues),
            }
        elif venue.get("history") and len(clean_text(venue["history"])) > len(venues[vid].get("history") or ""):
            venues[vid]["history"] = clean_text(venue["history"])

    edition_venues = [{"edition_id": EDITION_ID, "venue_id": vid} for vid in venues]

    projects: list[dict[str, Any]] = []
    artworks: list[dict[str, Any]] = []
    contributors: list[dict[str, Any]] = []
    project_by_title_slug: dict[str, str] = {}

    for project in projects_raw:
        zone_no = project.get("zoneNumber")
        zid = f"zone-{zone_no}" if zone_no else None
        title = one_line(project["title"].replace("\n", " — "))
        pid = project["id"]
        vid = venue_id_from_name(project.get("venue") or "")
        projects.append(
            {
                "id": pid,
                "edition_id": EDITION_ID,
                "zone_id": zid,
                "project_number": project.get("projectNumber"),
                "title": title,
                "sort_order": project.get("projectNumber"),
                "published": True,
            }
        )
        art_slug = unique_slug(slugs_taken, slugify(title), pid)
        art_id = f"artwork-{art_slug}"
        artworks.append(
            {
                "id": art_id,
                "project_id": pid,
                "edition_id": EDITION_ID,
                "zone_id": zid,
                "venue_id": vid,
                "title": title,
                "slug": art_slug,
                "description": clean_text(project.get("description")) or None,
                "materials_summary": one_line(project.get("materials")) or None,
                "dimensions_summary": one_line(project.get("dimensions")) or None,
                "sort_order": project.get("projectNumber"),
                "published": True,
            }
        )
        add_slug(art_slug, "artwork", art_id, EDITION_ID)
        project_by_title_slug[slugify(title)] = pid
        source("artwork", art_id, "sheet", f"Artworks Data row {project.get('sourceRow')}")
        artist_names: list[str] = []
        inst_names: list[str] = []
        for index, contrib in enumerate(project.get("contributors") or []):
            name = one_line(contrib.get("name"))
            if not name:
                continue
            artist_names.append(name)
            cpid = add_person(name, collective=is_collective(name))
            inst_name = one_line((contrib.get("institution") or "").replace("\n", " "))
            iid = add_institution(inst_name) if inst_name else None
            if inst_name:
                inst_names.append(inst_name)
            contributors.append(
                {
                    "id": f"{art_id}-c{index + 1}",
                    "artwork_id": art_id,
                    "person_id": cpid,
                    "display_name": name,
                    "institution_id": iid,
                    "institution_name": inst_name or None,
                    "materials": one_line(contrib.get("materials")) or None,
                    "dimensions": one_line(contrib.get("dimensions")) or None,
                    "sort_order": index,
                }
            )
        venue_name = VENUE_NAMES.get(vid or "", project.get("venue") or "")
        search_entries.append(
            {
                "id": f"search-{art_id}",
                "entity_type": "artwork",
                "entity_id": art_id,
                "edition_id": EDITION_ID,
                "title": title,
                "subtitle": " · ".join(part for part in [", ".join(artist_names), venue_name, f"Zone {zone_no}" if zone_no else ""] if part),
                "route": f"/editions/2025-26/artworks/{art_id}",
                "field_title": title,
                "field_artist": ", ".join(artist_names) or None,
                "field_curator": None,
                "field_venue": venue_name or None,
                "field_zone": f"Zone {zone_no}" if zone_no else None,
                "field_institution": ", ".join(inst_names) or None,
                "field_edition": "2025-26",
                "field_programme": None,
            }
        )

    programmes: list[dict[str, Any]] = []
    facilitators: list[dict[str, Any]] = []
    programme_links: list[dict[str, Any]] = []
    sort_prog = 0

    def add_facilitators(programme_id: str, raw: str) -> None:
        if not raw:
            return
        names = split_assistant_names(raw.replace(", and ", ", ").replace(" and ", ", "))
        if len(names) <= 1 and raw:
            names = [one_line(raw)]
        for index, name in enumerate(names):
            lowered = name.lower()
            if not name or lowered.startswith(("convened by", "in collaboration", "accompanied by")):
                continue
            pid = (
                add_person(name)
                if len(name.split()) <= 8 and "collaboration" not in lowered
                else None
            )
            facilitators.append(
                {
                    "programme_id": programme_id,
                    "person_id": pid,
                    "display_name": name,
                    "sort_order": index,
                }
            )

    def link_artworks(programme_id: str, titles: list[str]) -> None:
        seen: set[str] = set()
        for title in titles:
            pid = project_by_title_slug.get(slugify(title))
            if not pid:
                pid = project_by_title_slug.get(slugify(re.sub(r",?\s*2025$", "", title)))
            if pid and pid not in seen:
                seen.add(pid)
                programme_links.append({"programme_id": programme_id, "project_id": pid})

    workshop_doc = next(
        (d for d in (site.get("programmes") or {}).get("documents") or [] if "workshop" in (d.get("id") or "") or "ws" in (d.get("id") or "")),
        None,
    )
    if workshop_doc:
        for section in workshop_doc.get("sections") or []:
            parsed = parse_workshop_section(section)
            parsed["sort_order"] = sort_prog
            parsed["published"] = True
            fac_raw = parsed.pop("facilitators_raw")
            parsed.pop("image_urls", None)
            parsed.pop("source_heading", None)
            programmes.append(parsed)
            add_facilitators(parsed["id"], fac_raw)
            add_slug(parsed["slug"], "programme", parsed["id"], EDITION_ID)
            source("programme", parsed["id"], "docx", workshop_doc.get("path") or "workshops")
            search_entries.append(
                {
                    "id": f"search-{parsed['id']}",
                    "entity_type": "programme",
                    "entity_id": parsed["id"],
                    "edition_id": EDITION_ID,
                    "title": parsed["title"],
                    "subtitle": parsed.get("place") or "Workshop",
                    "route": f"/programmes#{parsed['slug']}",
                    "field_title": parsed["title"],
                    "field_artist": None,
                    "field_curator": None,
                    "field_venue": None,
                    "field_zone": None,
                    "field_institution": None,
                    "field_edition": "2025-26",
                    "field_programme": parsed["title"],
                }
            )
            sort_prog += 1

    awards_doc = next(
        (d for d in (site.get("programmes") or {}).get("documents") or [] if "award" in (d.get("id") or "")),
        None,
    )
    if awards_doc:
        for section in awards_doc.get("sections") or []:
            heading = clean_text(section.get("heading") or "")
            hid = section.get("id") or ""
            paras = section_paragraphs(section)
            if hid == "tab-1" or heading.lower().startswith("tab"):
                continue
            urls = section_urls(section)
            if "international" in hid or "international" in heading.lower():
                subtype = "international-award"
                title = "Tata Trusts Students’ Biennale International Awards"
                winners = parse_awardees(paras)
                body = "Tata Trusts Students’ Biennale International Awardees:\n\n" + winners_body(winners)
                link_titles = [w["artwork"] for w in winners if w.get("artwork")]
            elif "national" in hid or "national" in heading.lower():
                subtype = "national-award"
                title = "Tata Trusts Students’ Biennale National Awards"
                winners = parse_awardees(paras)
                body = "Tata Trusts Students’ Biennale National Awardees:\n\n" + winners_body(winners)
                link_titles = [w["artwork"] for w in winners if w.get("artwork")]
            elif "marseille" in hid or "beaux" in heading.lower() or "residency" in heading.lower():
                subtype = "residency"
                title = "Students’ Biennale 2025–26 × Beaux Arts de Marseille"
                if heading and "…" not in heading and "..." not in heading:
                    title = heading
                body = "\n\n".join(
                    p for p in paras if not p.startswith("http") and not p.lower().startswith("links to")
                )
                winners = []
                link_titles = []
            else:
                continue
            slug = slugify(hid or title)
            pid = f"programme-{slug}"
            programmes.append(
                {
                    "id": pid,
                    "subtype": subtype,
                    "state": "past",
                    "title": title,
                    "slug": slug,
                    "summary": one_line(body)[:280],
                    "body": body,
                    "dates": "2025-26",
                    "place": None,
                    "sort_order": sort_prog,
                    "published": True,
                }
            )
            add_slug(slug, "programme", pid, EDITION_ID)
            link_artworks(pid, link_titles)
            source("programme", pid, "docx", awards_doc.get("path") or "awards")
            search_entries.append(
                {
                    "id": f"search-{pid}",
                    "entity_type": "programme",
                    "entity_id": pid,
                    "edition_id": EDITION_ID,
                    "title": title,
                    "subtitle": heading or None,
                    "route": f"/programmes#{slug}",
                    "field_title": title,
                    "field_artist": None,
                    "field_curator": None,
                    "field_venue": None,
                    "field_zone": None,
                    "field_institution": None,
                    "field_edition": "2025-26",
                    "field_programme": title,
                }
            )
            sort_prog += 1

    residency_doc = next(
        (d for d in (site.get("programmes") or {}).get("documents") or [] if "residency" in (d.get("id") or "")),
        None,
    )
    if residency_doc:
        paras: list[str] = []
        for section in residency_doc.get("sections") or []:
            paras.extend(section_paragraphs(section))
        title = next((p for p in paras if "residency" in p.lower() and len(p) < 120), None) or "KBF × Students' Biennale Residency"
        body_parts = [p for p in paras if not p.startswith("http") and not p.lower().startswith("links to")]
        host = next((p for p in paras if p.lower().startswith("residency host")), "")
        period = ""
        place = ""
        for p in paras:
            if "residency period" in p.lower() or "venue:" in p.lower() or "awardees:" in p.lower():
                for line in p.split("\n"):
                    if "period" in line.lower():
                        period = one_line(line.split(":", 1)[-1])
                    if line.lower().startswith("venue"):
                        place = one_line(line.split(":", 1)[-1])
        slug = "kbf-sb-residency-sms-hall"
        pid = f"programme-{slug}"
        programmes.append(
            {
                "id": pid,
                "subtype": "residency",
                "state": "past",
                "title": one_line(title),
                "slug": slug,
                "summary": one_line(body_parts[1] if len(body_parts) > 1 else (body_parts[0] if body_parts else ""))[:280],
                "body": "\n\n".join(body_parts),
                "dates": period or None,
                "place": place or None,
                "sort_order": sort_prog,
                "published": True,
            }
        )
        add_slug(slug, "programme", pid, EDITION_ID)
        source("programme", pid, "docx", residency_doc.get("path") or "residency")
        if host:
            add_facilitators(pid, host.split(":", 1)[-1])
        link_artworks(pid, ["Shifting Landscapes"])  # Reppandee Lepcha
        # Durgesh Prajapati artwork unknown in this sheet; skip
        search_entries.append(
            {
                "id": f"search-{pid}",
                "entity_type": "programme",
                "entity_id": pid,
                "edition_id": EDITION_ID,
                "title": one_line(title),
                "subtitle": place or "Residency",
                "route": f"/programmes#{slug}",
                "field_title": one_line(title),
                "field_artist": None,
                "field_curator": None,
                "field_venue": place or None,
                "field_zone": None,
                "field_institution": None,
                "field_edition": "2025-26",
                "field_programme": one_line(title),
            }
        )
        sort_prog += 1

    press_items: list[dict[str, Any]] = []
    pending_title = ""
    press_sort = 0
    for doc in (site.get("press") or {}).get("documents") or []:
        for section in doc.get("sections") or []:
            for para in section.get("paragraphs") or []:
                text = clean_text(para.get("text") if isinstance(para, dict) else para)
                if not text:
                    continue
                urls = extract_urls(text) or list(para.get("links") or []) if isinstance(para, dict) else extract_urls(text)
                if not urls and not text.startswith("http"):
                    if text.lower().startswith("link to"):
                        pending_title = re.sub(r"^link to\s+", "", text, flags=re.I).strip(" :")
                    continue
                for url in urls or [text]:
                    if not url.startswith("http"):
                        continue
                    path = urlparse(url).path.strip("/")
                    last = path.split("/")[-1] if path else urlparse(url).netloc
                    derived = one_line(last.replace("-", " ").replace("_", " "))
                    title = pending_title or (derived[:120] if derived else url)
                    pending_title = ""
                    slug = unique_slug(slugs_taken, slugify(title) or f"press-{press_sort}", f"press-{press_sort}")
                    iid = f"press-{slug}"
                    press_items.append(
                        {
                            "id": iid,
                            "title": title[:200],
                            "slug": slug,
                            "excerpt": None,
                            "body": None,
                            "external_url": url,
                            "published_at": None,
                            "sort_order": press_sort,
                            "published": True,
                        }
                    )
                    add_slug(slug, "press_item", iid, None)
                    search_entries.append(
                        {
                            "id": f"search-{iid}",
                            "entity_type": "press_item",
                            "entity_id": iid,
                            "edition_id": None,
                            "title": title[:200],
                            "subtitle": urlparse(url).netloc,
                            "route": f"/press#{slug}",
                            "field_title": title[:200],
                            "field_artist": None,
                            "field_curator": None,
                            "field_venue": None,
                            "field_zone": None,
                            "field_institution": None,
                            "field_edition": None,
                            "field_programme": None,
                        }
                    )
                    press_sort += 1

    about_sections: list[dict[str, Any]] = []
    for index, section in enumerate(about.get("sections") or []):
        heading = section.get("heading") or ""
        slug = section.get("id") or slugify(heading)
        about_sections.append(
            {
                "id": section.get("id") or f"about-{slug}",
                "heading": heading,
                "slug": slug,
                "body": clean_text(section.get("body")) or None,
                "sort_order": index,
                "published": True,
            }
        )
        add_slug(slug, "about_section", section.get("id") or f"about-{slug}", None)

    sponsors: list[dict[str, Any]] = []
    sponsor_section = next(
        (s for s in about.get("documentSections") or [] if "sponsor" in (s.get("heading") or "").lower()),
        None,
    )
    if sponsor_section:
        for index, name in enumerate(section_paragraphs(sponsor_section)):
            if not name or name.startswith("⚠️"):
                continue
            sid = f"sponsor-{slugify(name)}"
            sponsors.append(
                {
                    "id": sid,
                    "edition_id": EDITION_ID,
                    "name": one_line(name),
                    "tier": None,
                    "url": None,
                    "sort_order": index,
                }
            )

    assets: list[dict[str, Any]] = []
    asset_links: list[dict[str, Any]] = []
    project_to_artwork = {row["project_id"]: row["id"] for row in artworks}
    curator_name_to_person = {people[pid]["name"]: pid for pid in people}
    seen_paths: set[str] = set()
    cover_assigned: set[tuple[str, str]] = set()

    for file_entry in media.get("files") or []:
        if file_entry.get("status") not in {None, "ok"} and file_entry.get("status") not in {"ok", "cached"}:
            continue
        path = file_entry.get("path") or file_entry.get("storagePath")
        if not path or path in seen_paths:
            continue
        seen_paths.add(path)
        sha = file_entry.get("sha256") or ""
        aid = f"asset-{sha[:24]}" if len(sha) >= 24 else f"asset-{slugify(path)}"
        if any(a["id"] == aid for a in assets):
            aid = f"asset-{slugify(path)}"
        if any(a["id"] == aid for a in assets):
            aid = f"{aid}-{len(assets)}"
        mime = file_entry.get("contentType") or file_entry.get("mime_type")
        assets.append(
            {
                "id": aid,
                "bucket": "sb-assets-original",
                "storage_path": path,
                "public_url": None,
                "parent_asset_id": None,
                "variant": "original",
                "mime_type": mime,
                "bytes": file_entry.get("bytes"),
                "width": file_entry.get("width"),
                "height": file_entry.get("height"),
                "sha256": sha or None,
                "alt_text": file_entry.get("label") or file_entry.get("entityId"),
                "sort_order": len(assets),
                "status": "pending",
                "source_url": file_entry.get("sourceUrl") or file_entry.get("url"),
                "source_label": Path(path).name,
            }
        )
        entity_type = file_entry.get("entityType")
        entity_id = file_entry.get("entityId")
        link_type = None
        link_id = None
        if entity_type == "artwork":
            link_type = "artwork"
            link_id = project_to_artwork.get(entity_id)
        elif entity_type == "venue":
            link_type = "venue"
            link_id = canon_venue_id(entity_id) if entity_id else None
            if link_id not in venues:
                link_id = None
        elif entity_type == "curator":
            link_type = "person"
            # curator-z1-savyasachi-anju-prabir → person-savyasachi-anju-prabir
            guess = entity_id.split("-", 2)[-1] if entity_id else ""
            link_id = f"person-{guess}" if guess else None
            if link_id not in people:
                link_id = None
                for name, pid in curator_name_to_person.items():
                    if guess and slugify(name) == guess:
                        link_id = pid
                        break
        if link_type and link_id:
            key = (link_type, link_id)
            role = "cover" if key not in cover_assigned else "gallery"
            if role == "cover":
                cover_assigned.add(key)
            if link_type == "person":
                role = "portrait" if role == "cover" else "gallery"
            asset_links.append(
                {
                    "asset_id": aid,
                    "entity_type": link_type,
                    "entity_id": link_id,
                    "role": role,
                }
            )
            card_path = card_storage_path(path)
            card_id = f"{aid}-card"
            assets.append(
                {
                    "id": card_id,
                    "bucket": "sb-assets-public",
                    "storage_path": card_path,
                    "public_url": public_asset_url(card_path),
                    "parent_asset_id": aid,
                    "variant": "card",
                    "mime_type": "image/jpeg",
                    "bytes": None,
                    "width": None,
                    "height": None,
                    "sha256": None,
                    "alt_text": file_entry.get("label") or file_entry.get("entityId"),
                    "sort_order": len(assets),
                    "status": "ready",
                    "source_url": file_entry.get("sourceUrl") or file_entry.get("url"),
                    "source_label": Path(path).name,
                }
            )
            asset_links.append(
                {
                    "asset_id": card_id,
                    "entity_type": link_type,
                    "entity_id": link_id,
                    "role": role,
                }
            )

    # Ensure people/institution slugs recorded
    for person in people.values():
        add_slug(person["slug"], "person", person["id"], EDITION_ID)
    for inst in institutions.values():
        add_slug(inst["slug"], "institution", inst["id"], None)

    payload = {
        "editions": editions,
        "zones": [zones[k] for k in sorted(zones)],
        "people": list(people.values()),
        "zone_people": zone_people,
        "institutions": list(institutions.values()),
        "venues": list(venues.values()),
        "edition_venues": edition_venues,
        "projects": projects,
        "artworks": artworks,
        "artwork_contributors": contributors,
        "programmes": programmes,
        "programme_ids": [p["id"] for p in programmes],
        "programme_facilitators": facilitators,
        "programme_project_links": programme_links,
        "press_items": press_items,
        "about_sections": about_sections,
        "sponsors": sponsors,
        "edition_sections": edition_sections,
        "edition_section_items": [
            item
            for item in edition_section_items
            if item["section_id"] in {s["id"] for s in edition_sections}
        ],
        "slugs": slugs,
        "assets": assets,
        "asset_links": asset_links,
        "search_entries": search_entries,
        "import_sources": import_sources,
        "imported_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
    }
    payload["catalogue_snapshots"] = build_catalogue_snapshots(payload)
    stats = {key: len(value) for key, value in payload.items() if isinstance(value, list)}
    return payload, stats


UPSERT_TABLES = [
    (
        "editions",
        "id, number, years, title, slug, overview, overall_curatorial_note, is_current, published",
        "id text, number int, years text, title text, slug text, overview text, overall_curatorial_note text, is_current boolean, published boolean",
        "id",
        "number = excluded.number, years = excluded.years, title = excluded.title, slug = excluded.slug, overview = excluded.overview, overall_curatorial_note = excluded.overall_curatorial_note, is_current = excluded.is_current, published = excluded.published",
    ),
    (
        "zones",
        "id, edition_id, number, label, region, common_curatorial_note, sort_order",
        "id text, edition_id text, number int, label text, region text, common_curatorial_note text, sort_order int",
        "id",
        "edition_id = excluded.edition_id, number = excluded.number, label = excluded.label, region = excluded.region, common_curatorial_note = excluded.common_curatorial_note, sort_order = excluded.sort_order",
    ),
    (
        "people",
        "id, name, slug, bio, is_collective",
        "id text, name text, slug text, bio text, is_collective boolean",
        "id",
        "name = excluded.name, slug = excluded.slug, bio = excluded.bio, is_collective = excluded.is_collective",
    ),
    (
        "zone_people",
        "zone_id, person_id, role, individual_curatorial_note, sort_order",
        "zone_id text, person_id text, role public.zone_person_role, individual_curatorial_note text, sort_order int",
        "zone_id, person_id, role",
        "individual_curatorial_note = excluded.individual_curatorial_note, sort_order = excluded.sort_order",
    ),
    (
        "institutions",
        "id, name, slug",
        "id text, name text, slug text",
        "id",
        "name = excluded.name, slug = excluded.slug",
    ),
    (
        "venues",
        "id, slug, name, history, map_url, virtual_tour_url, sort_order",
        "id text, slug text, name text, history text, map_url text, virtual_tour_url text, sort_order int",
        "id",
        "slug = excluded.slug, name = excluded.name, history = excluded.history, map_url = excluded.map_url, virtual_tour_url = excluded.virtual_tour_url, sort_order = excluded.sort_order",
    ),
    (
        "edition_venues",
        "edition_id, venue_id",
        "edition_id text, venue_id text",
        "edition_id, venue_id",
        "edition_id = excluded.edition_id",
    ),
    (
        "projects",
        "id, edition_id, zone_id, project_number, title, sort_order, published",
        "id text, edition_id text, zone_id text, project_number int, title text, sort_order int, published boolean",
        "id",
        "edition_id = excluded.edition_id, zone_id = excluded.zone_id, project_number = excluded.project_number, title = excluded.title, sort_order = excluded.sort_order, published = excluded.published",
    ),
    (
        "artworks",
        "id, project_id, edition_id, zone_id, venue_id, title, slug, description, materials_summary, dimensions_summary, sort_order, published",
        "id text, project_id text, edition_id text, zone_id text, venue_id text, title text, slug text, description text, materials_summary text, dimensions_summary text, sort_order int, published boolean",
        "id",
        "project_id = excluded.project_id, edition_id = excluded.edition_id, zone_id = excluded.zone_id, venue_id = excluded.venue_id, title = excluded.title, slug = excluded.slug, description = excluded.description, materials_summary = excluded.materials_summary, dimensions_summary = excluded.dimensions_summary, sort_order = excluded.sort_order, published = excluded.published",
    ),
    (
        "artwork_contributors",
        "id, artwork_id, person_id, display_name, institution_id, institution_name, materials, dimensions, sort_order",
        "id text, artwork_id text, person_id text, display_name text, institution_id text, institution_name text, materials text, dimensions text, sort_order int",
        "id",
        "artwork_id = excluded.artwork_id, person_id = excluded.person_id, display_name = excluded.display_name, institution_id = excluded.institution_id, institution_name = excluded.institution_name, materials = excluded.materials, dimensions = excluded.dimensions, sort_order = excluded.sort_order",
    ),
    (
        "programmes",
        "id, subtype, state, title, slug, summary, body, dates, place, sort_order, published",
        "id text, subtype public.programme_subtype, state public.programme_state, title text, slug text, summary text, body text, dates text, place text, sort_order int, published boolean",
        "id",
        "subtype = excluded.subtype, state = excluded.state, title = excluded.title, slug = excluded.slug, summary = excluded.summary, body = excluded.body, dates = excluded.dates, place = excluded.place, sort_order = excluded.sort_order, published = excluded.published",
    ),
    (
        "programme_project_links",
        "programme_id, project_id",
        "programme_id text, project_id text",
        "programme_id, project_id",
        "programme_id = excluded.programme_id",
    ),
    (
        "press_items",
        "id, title, slug, excerpt, body, external_url, published_at, sort_order, published",
        "id text, title text, slug text, excerpt text, body text, external_url text, published_at date, sort_order int, published boolean",
        "id",
        "title = excluded.title, slug = excluded.slug, excerpt = excluded.excerpt, body = excluded.body, external_url = excluded.external_url, published_at = excluded.published_at, sort_order = excluded.sort_order, published = excluded.published",
    ),
    (
        "about_sections",
        "id, heading, slug, body, sort_order, published",
        "id text, heading text, slug text, body text, sort_order int, published boolean",
        "id",
        "heading = excluded.heading, slug = excluded.slug, body = excluded.body, sort_order = excluded.sort_order, published = excluded.published",
    ),
    (
        "sponsors",
        "id, edition_id, name, tier, url, sort_order",
        "id text, edition_id text, name text, tier text, url text, sort_order int",
        "id",
        "edition_id = excluded.edition_id, name = excluded.name, tier = excluded.tier, url = excluded.url, sort_order = excluded.sort_order",
    ),
    (
        "edition_sections",
        "id, edition_id, section_key, title, body, sort_order",
        "id text, edition_id text, section_key public.edition_section_key, title text, body text, sort_order int",
        "id",
        "edition_id = excluded.edition_id, section_key = excluded.section_key, title = excluded.title, body = excluded.body, sort_order = excluded.sort_order",
    ),
    (
        "edition_section_items",
        "id, section_id, label, url, content_type, sort_order",
        "id text, section_id text, label text, url text, content_type text, sort_order int",
        "id",
        "section_id = excluded.section_id, label = excluded.label, url = excluded.url, content_type = excluded.content_type, sort_order = excluded.sort_order",
    ),
    (
        "slugs",
        "slug, entity_type, entity_id, edition_id",
        "slug text, entity_type text, entity_id text, edition_id text",
        "slug",
        "entity_type = excluded.entity_type, entity_id = excluded.entity_id, edition_id = excluded.edition_id",
    ),
    (
        "assets",
        "id, bucket, storage_path, public_url, parent_asset_id, variant, mime_type, bytes, width, height, sha256, alt_text, sort_order, status, source_url, source_label",
        "id text, bucket text, storage_path text, public_url text, parent_asset_id text, variant public.asset_variant, mime_type text, bytes bigint, width int, height int, sha256 text, alt_text text, sort_order int, status public.asset_status, source_url text, source_label text",
        "id",
        "bucket = excluded.bucket, storage_path = excluded.storage_path, public_url = excluded.public_url, parent_asset_id = excluded.parent_asset_id, variant = excluded.variant, mime_type = excluded.mime_type, bytes = excluded.bytes, width = excluded.width, height = excluded.height, sha256 = excluded.sha256, alt_text = excluded.alt_text, sort_order = excluded.sort_order, status = excluded.status, source_url = excluded.source_url, source_label = excluded.source_label",
    ),
    (
        "asset_links",
        "asset_id, entity_type, entity_id, role",
        "asset_id text, entity_type public.asset_entity_type, entity_id text, role public.asset_role",
        "asset_id, entity_type, entity_id, role",
        "asset_id = excluded.asset_id",
    ),
    (
        "search_entries",
        "id, entity_type, entity_id, edition_id, title, subtitle, route, field_title, field_artist, field_curator, field_venue, field_zone, field_institution, field_edition, field_programme",
        "id text, entity_type text, entity_id text, edition_id text, title text, subtitle text, route text, field_title text, field_artist text, field_curator text, field_venue text, field_zone text, field_institution text, field_edition text, field_programme text",
        "id",
        "entity_type = excluded.entity_type, entity_id = excluded.entity_id, edition_id = excluded.edition_id, title = excluded.title, subtitle = excluded.subtitle, route = excluded.route, field_title = excluded.field_title, field_artist = excluded.field_artist, field_curator = excluded.field_curator, field_venue = excluded.field_venue, field_zone = excluded.field_zone, field_institution = excluded.field_institution, field_edition = excluded.field_edition, field_programme = excluded.field_programme",
    ),
    (
        "catalogue_snapshots",
        "edition_id, payload, search_index, generated_at",
        "edition_id text, payload jsonb, search_index jsonb, generated_at timestamptz",
        "edition_id",
        "payload = excluded.payload, search_index = excluded.search_index, generated_at = excluded.generated_at",
    ),
]


def render_sql(payload: dict[str, Any]) -> str:
    blob = json.dumps(payload, ensure_ascii=False, default=str)
    if "$catalogue$" in blob:
        raise SystemExit("payload contains dollar-quote delimiter")
    parts = [
        "begin;",
        "create temporary table import_payload (doc jsonb);",
        f"insert into import_payload (doc) values ($catalogue${blob}$catalogue$::jsonb);",
        """
delete from public.programme_facilitators
where programme_id in (
  select jsonb_array_elements_text(doc -> 'programme_ids') from import_payload
);
""",
    ]
    for table, cols, record, conflict, updates in UPSERT_TABLES:
        parts.append(
            f"""
insert into public.{table} ({cols})
select {cols}
from jsonb_to_recordset((select doc -> '{table}' from import_payload)) as x({record})
on conflict ({conflict}) do update set {updates};
"""
        )
    parts.append(
        """
insert into public.programme_facilitators (programme_id, person_id, display_name, sort_order)
select programme_id, person_id, display_name, sort_order
from jsonb_to_recordset((select doc -> 'programme_facilitators' from import_payload))
  as x(programme_id text, person_id text, display_name text, sort_order int);

insert into public.import_sources (entity_type, entity_id, source_type, source_ref)
select entity_type, entity_id, source_type, source_ref
from jsonb_to_recordset((select doc -> 'import_sources' from import_payload))
  as x(entity_type text, entity_id text, source_type text, source_ref text);

commit;
"""
    )
    return "\n".join(parts)


def apply_sql(path: Path, target: str) -> None:
    flag = "--linked" if target == "linked" else "--local"
    cmd = [
        "supabase",
        "--workdir",
        "database",
        "db",
        "query",
        flag,
        "--file",
        str(path),
    ]
    print("Running", " ".join(cmd), file=sys.stderr)
    subprocess.run(cmd, cwd=ROOT, check=True)


def load_env() -> None:
    env_path = Path(__file__).resolve().parent / ".env.local"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, value = line.split("=", 1)
        os.environ.setdefault(name.strip(), value.strip())


def rest_upsert(table: str, rows: list[dict[str, Any]], conflict: str, key: str, url: str) -> None:
    if not rows:
        return
    endpoint = f"{url}/rest/v1/{table}?on_conflict={conflict}"
    batch = 80
    for i in range(0, len(rows), batch):
        chunk = rows[i : i + batch]
        body = json.dumps(chunk, ensure_ascii=False, default=str).encode("utf-8")
        req = urllib.request.Request(endpoint, data=body, method="POST")
        req.add_header("Authorization", f"Bearer {key}")
        req.add_header("apikey", key)
        req.add_header("Content-Type", "application/json")
        req.add_header("Prefer", "resolution=merge-duplicates,return=minimal")
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                resp.read()
        except urllib.error.HTTPError as err:
            detail = err.read().decode("utf-8", "replace")
            raise SystemExit(f"{table} upsert failed ({err.code}): {detail}") from err
        print(f"  {table} {min(i + batch, len(rows))}/{len(rows)}", file=sys.stderr)


def apply_rest(payload: dict[str, Any]) -> None:
    load_env()
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if not key:
        raise SystemExit("Set SUPABASE_SERVICE_ROLE_KEY (backend/.env.local)")
    url = os.environ.get("SUPABASE_URL", PUBLIC_SUPABASE_URL)
    print(f"Upserting catalogue via REST to {url}", file=sys.stderr)
    assets = payload["assets"]
    rest_upsert("assets", [a for a in assets if a.get("variant") != "card"], "id", key, url)
    rest_upsert("assets", [a for a in assets if a.get("variant") == "card"], "id", key, url)
    rest_upsert("asset_links", payload["asset_links"], "asset_id,entity_type,entity_id,role", key, url)
    rest_upsert("catalogue_snapshots", payload["catalogue_snapshots"], "edition_id", key, url)


def main() -> None:
    parser = argparse.ArgumentParser(description="Import production catalogue into Supabase")
    parser.add_argument("--dry-run", action="store_true", help="Print counts and write SQL, do not apply")
    parser.add_argument("--target", choices=("local", "linked"), default="linked")
    parser.add_argument("--apply", choices=("sql", "rest"), default="rest")
    parser.add_argument("--sql-out", type=Path, default=SQL_OUT)
    args = parser.parse_args()

    payload, stats = build_payload()
    print(json.dumps(stats, indent=2))
    if args.dry_run:
        return
    if args.apply == "rest":
        apply_rest(payload)
        return
    args.sql_out.parent.mkdir(parents=True, exist_ok=True)
    sql = render_sql(payload)
    args.sql_out.write_text(sql, encoding="utf-8")
    print(f"Wrote {args.sql_out} ({args.sql_out.stat().st_size} bytes)", file=sys.stderr)
    apply_sql(args.sql_out, args.target)


if __name__ == "__main__":
    main()
